// <auto-generated />
using System;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20260407152206_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessLogic.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BusinessLogic.Entities.PetGroomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PetGroomers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fb87e5b-89e4-488d-8f20-49299c1c3d53"),
                            UserId = "G-01"
                        },
                        new
                        {
                            Id = new Guid("4d1d2047-8020-473b-a293-35f6d43b0314"),
                            UserId = "G-02"
                        },
                        new
                        {
                            Id = new Guid("2864b026-1c02-4e02-8a77-944aa4fa7e87"),
                            UserId = "G-03"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Entities.Reserve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.Property<string>("PetSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReminderJobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Reserves");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PetGroomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PetGroomerId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Date = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4fb87e5b-89e4-488d-8f20-49299c1c3d53"),
                            StartTime = new DateTime(2026, 4, 7, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Date = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4d1d2047-8020-473b-a293-35f6d43b0314"),
                            StartTime = new DateTime(2026, 4, 7, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Date = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("2864b026-1c02-4e02-8a77-944aa4fa7e87"),
                            StartTime = new DateTime(2026, 4, 7, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Date = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4fb87e5b-89e4-488d-8f20-49299c1c3d53"),
                            StartTime = new DateTime(2026, 4, 8, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Date = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4d1d2047-8020-473b-a293-35f6d43b0314"),
                            StartTime = new DateTime(2026, 4, 8, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Date = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("2864b026-1c02-4e02-8a77-944aa4fa7e87"),
                            StartTime = new DateTime(2026, 4, 8, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Date = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4fb87e5b-89e4-488d-8f20-49299c1c3d53"),
                            StartTime = new DateTime(2026, 4, 9, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Date = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4d1d2047-8020-473b-a293-35f6d43b0314"),
                            StartTime = new DateTime(2026, 4, 9, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Date = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("2864b026-1c02-4e02-8a77-944aa4fa7e87"),
                            StartTime = new DateTime(2026, 4, 9, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4fb87e5b-89e4-488d-8f20-49299c1c3d53"),
                            StartTime = new DateTime(2026, 4, 10, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4d1d2047-8020-473b-a293-35f6d43b0314"),
                            StartTime = new DateTime(2026, 4, 10, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("2864b026-1c02-4e02-8a77-944aa4fa7e87"),
                            StartTime = new DateTime(2026, 4, 10, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Date = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4fb87e5b-89e4-488d-8f20-49299c1c3d53"),
                            StartTime = new DateTime(2026, 4, 11, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Date = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4d1d2047-8020-473b-a293-35f6d43b0314"),
                            StartTime = new DateTime(2026, 4, 11, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Date = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("2864b026-1c02-4e02-8a77-944aa4fa7e87"),
                            StartTime = new DateTime(2026, 4, 11, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4fb87e5b-89e4-488d-8f20-49299c1c3d53"),
                            StartTime = new DateTime(2026, 4, 12, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4d1d2047-8020-473b-a293-35f6d43b0314"),
                            StartTime = new DateTime(2026, 4, 12, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("2864b026-1c02-4e02-8a77-944aa4fa7e87"),
                            StartTime = new DateTime(2026, 4, 12, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Date = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4fb87e5b-89e4-488d-8f20-49299c1c3d53"),
                            StartTime = new DateTime(2026, 4, 13, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Date = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4d1d2047-8020-473b-a293-35f6d43b0314"),
                            StartTime = new DateTime(2026, 4, 13, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Date = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("2864b026-1c02-4e02-8a77-944aa4fa7e87"),
                            StartTime = new DateTime(2026, 4, 13, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Date = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4fb87e5b-89e4-488d-8f20-49299c1c3d53"),
                            StartTime = new DateTime(2026, 4, 14, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Date = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4d1d2047-8020-473b-a293-35f6d43b0314"),
                            StartTime = new DateTime(2026, 4, 14, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Date = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("2864b026-1c02-4e02-8a77-944aa4fa7e87"),
                            StartTime = new DateTime(2026, 4, 14, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4fb87e5b-89e4-488d-8f20-49299c1c3d53"),
                            StartTime = new DateTime(2026, 4, 15, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("4d1d2047-8020-473b-a293-35f6d43b0314"),
                            StartTime = new DateTime(2026, 4, 15, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 4, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            PetGroomerId = new Guid("2864b026-1c02-4e02-8a77-944aa4fa7e87"),
                            StartTime = new DateTime(2026, 4, 15, 6, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BusinessLogic.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "G-01",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC_01",
                            CreatedAt = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ana@canina.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Ana Martínez",
                            NormalizedEmail = "ANA@CANINA.COM",
                            NormalizedUserName = "ANA@CANINA.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_01",
                            TwoFactorEnabled = false,
                            UserName = "ana@canina.com"
                        },
                        new
                        {
                            Id = "G-02",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC_02",
                            CreatedAt = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carlos@canina.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Carlos Pérez",
                            NormalizedEmail = "CARLOS@CANINA.COM",
                            NormalizedUserName = "CARLOS@CANINA.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_02",
                            TwoFactorEnabled = false,
                            UserName = "carlos@canina.com"
                        },
                        new
                        {
                            Id = "G-03",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CONC_03",
                            CreatedAt = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lucia@canina.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Lucía Gómez",
                            NormalizedEmail = "LUCIA@CANINA.COM",
                            NormalizedUserName = "LUCIA@CANINA.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_03",
                            TwoFactorEnabled = false,
                            UserName = "lucia@canina.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessLogic.Entities.Client", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("BusinessLogic.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessLogic.Entities.PetGroomer", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("BusinessLogic.Entities.PetGroomer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Reserve", b =>
                {
                    b.HasOne("BusinessLogic.Entities.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.Schedule", null)
                        .WithMany("Reservations")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Schedule", b =>
                {
                    b.HasOne("BusinessLogic.Entities.PetGroomer", null)
                        .WithMany("Schedules")
                        .HasForeignKey("PetGroomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusinessLogic.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLogic.Entities.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BusinessLogic.Entities.PetGroomer", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("BusinessLogic.Entities.Schedule", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
